/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    "docSidebar": [
        "overview",
        {
            "type": "category",
            "label": "Getting started",
            "items": [
                "getting-started/installation",
                "getting-started/usage",
                "getting-started/short-and-longhand"
            ],
            "link": {
                "type": "generated-index",
                "title": "Longer title for Getting Started",
                "description": "A brief description for this category index page."
            }
        },
        {
            "type": "category",
            "label": "Outline examples",
            "items": [
                "outline-examples/basic-single-sidebar",
                "outline-examples/long-and-shorthand-format",
                "outline-examples/topic-headings",
                "outline-examples/several-sidebars-in-a-file"
            ],
            "link": {
                "type": "generated-index",
                "title": "Outline examples",
                "description": "Examples of `.outline.yml` files, each file showing specific features"
            }
        },
        "outline-properties"
    ],
    "updateSidebar": [
        "updates/first",
        "updates/second"
    ],
    "tutorialSidebar": [
        "tutorials/tutorial-1",
        "tutorials/tutorial-2"
    ],
    "genericSidebar": []
}

module.exports = sidebars;