/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    "docSidebar": [
        "overview",
        {
            "type": "category",
            "label": "Getting started",
            "items": [
                "getting-started/installation",
                "getting-started/usage",
                "getting-started/documentation-outline"
            ],
            "link": {
                "type": "generated-index",
                "title": "Getting started"
            }
        },
        "outline-properties",
        {
            "type": "category",
            "label": "Use cases",
            "items": [
                "use-cases/github",
                "use-cases/jest",
                "use-cases/visual-studio-code",
                "use-cases/visual-studio-code-updates"
            ],
            "link": {
                "type": "generated-index",
                "title": "Use cases"
            }
        }
    ],
    "updateSidebar": [
        "updates/v23-4",
        "updates/v23-3"
    ]
}

module.exports = sidebars;