/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    "docsSidebar": [
        {
            "type": "category",
            "label": "My group items",
            "items": [
                "first-item-in-group",
                "second-item-in-group"
            ]
        },
        "index",
        {
            "type": "category",
            "label": "User Guides",
            "items": [
                "banking-product-factory",
                {
                    "type": "link",
                    "label": "Innovation Studio",
                    "href": "studio/22-1/user-guide/content"
                },
                "insurance-product-factory"
            ]
        }
    ],
    "innovationStudioSidebar": [
        {
            "type": "link",
            "label": "All Products",
            "href": "/docs/"
        },
        "studio/22-1/user-guide/content/index",
        {
            "type": "category",
            "label": "Getting started",
            "items": [
                "studio/22-1/user-guide/content/getting-started/installation",
                "studio/22-1/user-guide/content/getting-started/basic-concepts"
            ]
        },
        {
            "type": "category",
            "label": "Evolutive Data Core",
            "items": [
                "studio/22-1/user-guide/content/evolutive-data-core/data-model-designer",
                "studio/22-1/user-guide/content/evolutive-data-core/data-model-explorer",
                "studio/22-1/user-guide/content/evolutive-data-core/data-import-templates",
                "studio/22-1/user-guide/content/evolutive-data-core/data-governance",
                "studio/22-1/user-guide/content/evolutive-data-core/data-pipes"
            ],
            "link": {
                "type": "generated-index",
                "title": "Evolutive Data Core"
            }
        },
        "studio/22-1/user-guide/content/digital-experience",
        "studio/22-1/user-guide/content/automation-processors"
    ],
    "bankingProductFactorySidebar": [
        "ap/banking-product-factory/4-3/user-guide/content/index"
    ],
    "insuranceProductFactorySidebar": [
        "ap/insurance-product-factory/7-3/user-guide/content/index"
    ]
}

module.exports = sidebars;